@api_de_verdade_HostAddress = http://localhost:5007

GET {{api_de_verdade_HostAddress}}/categories/
Accept: application/json
###

GET {{api_de_verdade_HostAddress}}/categories/:id
Accept: application/json
###

POST {{api_de_verdade_HostAddress}}/categories
Accept: application/json
###

PUT {{api_de_verdade_HostAddress}}/categories/:id
Accept: application/json
###

DELETE {{api_de_verdade_HostAddress}}/categories/:id
Accept: application/json
###